// FreeSSHDService.idl : IDL source for FreeSSHDService.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (FreeSSHDService.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(F641DBB3-CBB1-47A3-A258-957DF1E10260),
	version(1.0),
	helpstring("FreeSSHDService 1.0 Type Library")
]
library FREESSHDSERVICELib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

};
