//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FreeSSHDService.rc
//
#define IDS_SERVICENAME                 100
#define IDR_FreeSSHDService             100
#define IDR_MAINFRAME                   128
#define IDD_MAINDLG                     129
#define IDD_BEGIN                       201
#define IDD_PAGE_STATUS                 202
#define IDD_PAGE_END                    203
#define IDD_PAGE_HOSTRESTRICTIONS       203
#define IDB_HEADER                      204
#define IDB_WATERMARK                   206
#define IDD_PAGE_TELNET                 207
#define IDD_PAGE_SSH                    208
#define IDD_PAGE_USERS                  209
#define IDI_OK                          211
#define IDI_BAD                         212
#define IDB_WEONLYDO                    214
#define IDD_PAGE_TUNNELING              215
#define IDD_PAGE_LOGGING                216
#define IDI_PAGE_FTP                    217
#define IDI_PAGE_SSH                    218
#define IDI_PAGE_USERS                  219
#define IDI_PAGE_HOSTRESTRICTIONS       220
#define IDI_PAGE_LOGGING                221
#define IDI_YES                         223
#define IDI_USER                        224
#define IDI_PAGE_TELNET                 225
#define IDI_NO                          226
#define IDR_MENU                        227
#define IDD_PAGE_CRYPTO                 229
#define IDI_PAGE_CRYPTO                 231
#define IDD_PAGE_SFTP                   232
#define IDI_PAGE_SFTP                   233
#define IDD_PAGE_AUTH                   234
#define IDI_PAGE_TUNNELING              236
#define IDI_PAGE_AUTH                   237
#define IDD_USERPAGE_1                  239
#define IDD_PAGE_ONLINEUSERS            240
#define IDD_PAGE_UPDATE                 241
#define IDD_MESSAGEDLG                  242
#define IDI_PAGE_UPDATE                 245
#define IDC_LBL_TITLE                   1000
#define IDC_STATIC_NEXT                 1001
#define IDC_LBL_WELCOME                 1002
#define IDC_FREESSHD                    1003
#define IDC_EDIT1                       1004
#define IDC_HOSTRESTRICTIONS_IPADDRESSES 1004
#define IDC_STATUS_SSHBALLOON           1004
#define IDC_STATUS_TELNETBALLOON        1005
#define IDC_USERS                       1007
#define IDC_SHELL                       1008
#define IDC_SFTP                        1009
#define IDC_TUNNELING                   1010
#define IDC_FTP                         1011
#define IDC_HOMEDIR                     1012
#define IDC_MAXTRANSFER                 1013
#define IDC_REPORT                      1015
#define IDC_STATUS_TELNET               1016
#define IDC_STATUS_SSH                  1017
#define IDC_STATUS_TELNET_USERS         1019
#define IDC_STATUS_TELNET_LINE1         1019
#define IDC_STATUS_SSH_LINE1            1020
#define IDC_TELNET_PIC                  1021
#define IDC_SSH_PIC                     1022
#define IDC_LABEL_VERSION               1023
#define IDC_STATUS_TELNET_LINE2         1024
#define IDC_STATUS_SSH_LINE2            1025
#define IDC_LABEL_POWEREDBY             1027
#define IDC_WEONLYDOLOGO                1028
#define IDC_TELNET_LISTENADDRESS        1029
#define IDC_TELNET_PORT                 1030
#define IDC_LABEL_TELNET_LISTENADDRESS  1031
#define IDC_LABEL_TELNET_PORT           1032
#define IDC_TELNET_GREETINGMESSAGE_BROWSE 1033
#define IDC_TELNET_BANNERMESSAGE_BROWSE 1033
#define IDC_TELNET_MAXCONNECTIONS       1034
#define IDC_LABEL_TELNET_MAXCONNECTIONS 1035
#define IDC_TELNET_IDLETIMEOUT          1036
#define IDC_LABEL_TELNET_IDLETIMEOUT    1037
#define IDC_LABEL_TELNET_IDLETIMEOUTSECONDS 1038
#define IDC_TELNET_GREETINGMESSAGE      1039
#define IDC_TELNET_BANNERMESSAGE        1039
#define IDC_LABEL_TELNET_GREETINGMESSAGE 1040
#define IDC_LABEL_TELNET_BANNERMESSAGE  1040
#define IDC_TELNET_GOODBYEMESSAGE       1041
#define IDC_LABEL_TELNET_GOODBYEMESSAGE 1042
#define IDC_TELNET_GOODBYEMESSAGE_BROWSE 1043
#define IDC_TELNET_ROOTDIR              1044
#define IDC_TELNET_CMD                  1044
#define IDC_LABEL_TELNET_ROOTDIR        1045
#define IDC_LABEL_TELNET_CMD            1045
#define IDC_TELNET_ROOTDIR_BROWSE       1046
#define IDC_TELNET_CMD_BROWSE           1046
#define IDC_TELNET_AUTOSTART            1047
#define IDC_TELNET_NEWCONSOLE           1048
#define IDC_LABEL_SSH_BANNERMESSAGE     1051
#define IDC_LABEL_SSH_CMD               1053
#define IDC_SSH_LISTENADDRESS           1054
#define IDC_SSH_PORT                    1055
#define IDC_SSH_MAXCONNECTIONS          1056
#define IDC_SSH_IDLETIMEOUT             1057
#define IDC_SSH_BANNERMESSAGE           1059
#define IDC_SSH_CMD                     1061
#define IDC_SSH_AUTOSTART               1062
#define IDC_SSH_CMD_BROWSE              1063
#define IDC_SSH_BANNERMESSAGE_BROWSE    1065
#define IDC_USERS_LIST                  1066
#define IDC_USERS_ADD                   1067
#define IDC_USERS_CHANGE                1068
#define IDC_HOSTRESTRICTIONS_ALLOW      1068
#define IDC_USERS_REMOVE                1069
#define IDC_HOSTRESTRICTIONS_REFUSE     1069
#define IDC_LABEL_HOSTRESTRICTIONS_HINT 1070
#define IDC_PAGEICON                    1072
#define IDC_LOGO                        1073
#define IDC_LABEL_SSH_RSAKEY            1089
#define IDC_SSH_RSAKEY                  1090
#define IDC_SSH_RSAKEY_BROWSE           1091
#define IDC_SSH_RSAKEY_NEW              1092
#define IDC_LABEL_SSH_RSAKEY_STATUS     1093
#define IDC_SSH_DSAKEY                  1094
#define IDC_CRYPTO_CIPHER_GROUP         1094
#define IDC_LABEL_SSH_DSAKEY            1095
#define IDC_CRYPTO_CIPHER_ANY           1095
#define IDC_SSH_DSAKEY_BROWSE           1096
#define IDC_CRYPTO_CIPHER_AES           1096
#define IDC_LABEL_SSH_DSAKEY_STATUS     1097
#define IDC_CRYPTO_CIPHER_AES128        1097
#define IDC_SSH_DSAKEY_NEW              1098
#define IDC_CRYPTO_CIPHER_AES192        1098
#define IDC_CRYPTO_CIPHER_AES256        1099
#define IDC_LABEL_SSH_RSAKEY_BITS       1099
#define IDC_CRYPTO_CIPHER_3DES          1100
#define IDC_LABEL_SSH_DSAKEY_BITS       1100
#define IDC_CRYPTO_CIPHER_BLOWFISH      1101
#define IDC_CRYPTO_CIPHER_CAST128       1102
#define IDC_CRYPTO_MACS_GROUP           1103
#define IDC_CRYPTO_MAC_MD5              1104
#define IDC_CRYPTO_MAC_HMAC             1105
#define IDC_LABEL_SSH_LISTENADDRESS     1106
#define IDC_LABEL_SSH_PORT              1107
#define IDC_LABEL_SSH_MAXCONNECTIONS    1108
#define IDC_LABEL_SSH_IDLETIMEOUTSECONDS 1109
#define IDC_LABEL_SFTP_HOME             1109
#define IDC_SFTP_HOME                   1110
#define IDC_SFTP_HOME_BROWSE            1111
#define IDC_LOGGING_LOGEVENTS           1113
#define IDC_LOGGING_LOGFILE             1114
#define IDC_LABEL_LOGGING_LOGFILE       1115
#define IDC_LOGGING_GROUP               1116
#define IDC_LOGGING_RESOLVEIP           1117
#define IDC_LOGGING_LOGFILE_BROWSE      1118
#define IDC_LABEL_AUTH_PASSWORD_GROUP   1119
#define IDC_AUTH_PASSWORD_DISABLED      1120
#define IDC_AUTH_PASSWORD_ALLOWED       1121
#define IDC_AUTH_PASSWORD_REQUIRED      1122
#define IDC_LABEL_AUTH_PUBLICKEY_GROUP  1123
#define IDC_AUTH_PUBLICKEY_DISABLED     1124
#define IDC_AUTH_PUBLICKEY_ALLOWED      1125
#define IDC_AUTH_PUBLICKEY_REQUIRED     1126
#define IDC_LABEL_AUTH_PUBLICKEYFOLDER  1127
#define IDC_AUTH_PUBLICKEYFOLDER        1128
#define IDC_AUTH_PUBLICKEYFOLDER_BROWSE 1129
#define IDC_TUNNELING_LOCAL             1131
#define IDC_LABEL_TUNNELING_LOCAL       1132
#define IDC_TUNNELING_LOCAL_ONLY        1133
#define IDC_TUNNELING_REMOTE            1134
#define IDC_LABEL_USERPAGE1_LOGIN       1134
#define IDC_LABEL_TUNNELING_REMOTE      1135
#define IDC_USERPAGE1_LOGIN             1135
#define IDC_TUNNELING_REMOTE_ONLY       1136
#define IDC_LABEL_USERPAGE1_AUTH        1136
#define IDC_USERPAGE1_AUTH              1137
#define IDC_USERPAGE1_PASSWORD          1138
#define IDC_LABEL_USERPAGE1_PASSWORD    1139
#define IDC_USERPAGE1_PASSWORD2         1140
#define IDC_LABEL_USERPAGE1_PASSWORD2   1141
#define IDC_USERPAGE1_DOMAIN            1142
#define IDC_LABEL_USERPAGE1_DOMAIN      1143
#define IDC_LABEL_USERPAGE1_USERCANUSE  1144
#define IDC_USERPAGE1_SHELL             1145
#define IDC_USERPAGE1_SFTP              1146
#define IDC_ONLINEUSERS_LIST            1146
#define IDC_USERPAGE1_TUNNELING         1147
#define IDC_ONLINEUSERS_DISCONNECT      1147
#define IDC_LOGGING_LOGFILE_OPEN        1148
#define IDC_LABEL_USERS_SHELL           1154
#define IDC_SSH_NEWCONSOLE              1155
#define IDC_LABEL_USERS_SFTP            1156
#define IDC_UPDATE_USE                  1156
#define IDC_LABEL_USERS_TUNNEL          1157
#define IDC_UPDATE_GROUP                1157
#define IDC_LABEL_USERS_LOGIN           1158
#define IDC_UPDATE_CHECKNOW             1159
#define IDC_UPDATE_CHECKONSTARTUP       1160
#define IDC_UPDATE_PROMPT               1162
#define IDC_UPDATE_OPTIONS              1164
#define IDC_UPDATE_DONTPROMPT           1165
#define IDC_UPDATE_SHOWMESSAGES         1166
#define IDC_MESSAGEDLG_CAPTION          1168
#define IDC_MESSAGEDLG_TEXT             1169
#define ID_POPUP_SETTINGS               32772
#define ID_POPUP_UNLOAD                 32773
#define ID_POPUP2_512BITS               32774
#define ID_POPUP2_1024BITS              32775
#define ID_POPUP2_2048BITS              32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        246
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1170
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
